### ISSUE TITLE
Mockup du clavier virtuel

### ISSUE THREAD

**Issue by reinepoire** [reinepoire/clavierVirtuel#1]
### Voici la schématisation grossière de mon clavier virtuel.

![image](https://user-images.githubusercontent.com/56972040/98356468-ebfb6f00-2023-11eb-8923-4dce58b947eb.png)

**Comment by Herondil** [comment]
Je pense que l'essentiel y est !

Est-ce que tu as prévu un panneau pour les caractères spéciaux ? Si oui il faut le maquetter je pense.
Est-ce qu'il y a un lien vers le projet sur github ?

Enfin, sur ce brouillon tu peux commencer à réfléchir à la couleur, mais généralement cela se fait sur un autre document, plus orienté sur la charte graphique !

**Comment by reinepoire** [comment]
J'ai pensé à la touche pour les caractères spéciaux mais pas forcément au panneau, ni au lien vers le projet Github. Je vais modifié le mockup en ayant ces remarques en tête, merci. 

J'ai déjà une charte graphique, je penserai à la mettre dans le projet :)

**Comment by Herondil** [comment]
Ah top ! On peut la voir quelque part ?

**Comment by reinepoire** [comment]
Oui, oui, je l'ai ajoutée à mon dépôt

**Comment by Herondil** [comment]
Est-ce qu'il s'agit bien de https://github.com/reinepoire/clavierVirtuel/blob/main/moodboard.pdf ?

**Comment by reinepoire** [comment]
C'est bien ça !

**Comment by Herondil** [comment]
Super ! Est-ce que tu as besoin de retours sur le choix des couleurs ? Peut-être que je peux trouver des personnes appropriées si tu as besoin.

**Comment by reinepoire** [comment]
Oui, pourquoi pas. Ça ne peut être que positif.
