### ISSUE TITLE
Effet au click ?

### ISSUE THREAD

**Issue by Herondil** [reinepoire/clavierVirtuel#2]
Je me demandais si tu avais prévu un effet lors du click sur une touche !

**Comment by reinepoire** [comment]
Oui. Je suis juste _**assez**_ indécise et j'hésite entre plusieurs options 🙈  : 

- Un effet au survol et pas d'effet au clic
- Un effet au survol et un effet au clic 
- Pas d'effet au survol et un effet au clic

Pour l'instant, j'ai mis un effet au survol mais je n'en suis pas convaincue. Du coup, j'ai pas encore "push le commit"

**Comment by reinepoire** [comment]
Je me suis enfin décidée et j'ai opté pour un effet au clic. Dans la version béta, il est au survol mais je vais changer ça.

**Comment by Herondil** [comment]
Ok, bonne idée je pense !
